### ISSUE TITLE
Let visitors fail the build

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/packman#10]
In case someone wants to lint at the same time (node-jshint), it would be good to have visitors have the ability to fail the build.

**Comment by captainbrosset** [comment]
Why not letting them just process.exit(1) ?

**Comment by piuccio** [comment]
I'm fine with `process.exit(1)`
That's what's suggested by [npm script documentation](https://npmjs.org/doc/scripts.html#EXITING)

It would be good anyway to write something in the documentation.

The added value of providing a way to let a visitor fail is that packman could add extra logging on which visitor caused the fail.

**Comment by captainbrosset** [comment]
So, 2 solutions:
- either a visitor deliberately wants to exit the build and it uses `process.exit(1)` . Already possible today and it means it's up to the visitor to log relevant information in that case.
- second is a new feature I'm working on which will exit the build as soon as a visitor crashes with an exception. Today's implementation just logs an error and skips the visitor. With a new setting I want to introduce, it could fail the build immediately.

**Comment by captainbrosset** [comment]
Implemented in af4d3476497760b1552765fe3a7a2a0fda060853

**Comment by captainbrosset** [comment]
Closed in 0.2.7
