### ISSUE TITLE
Stack exhaustion if too many input files

### ISSUE THREAD

**Issue by jakub-g** [captainbrosset/packman#14]
# Summary

If too many input files match the pattern in YAML config file, then visitors crash due to call stack exhaustion. This is due to callback nature of the application.
# Explanation

Nodejs run underlying V8 with the following stack-related defaults:

`node --stack-size=492 --stack-trace-limit=10`

This reads as:
stack size = 492 kB
stack trace limit = 10 frames when logging stack trace with `console.trace()` / `new Error().stack`.

If too many input files are specified, the stack size is exhausted, because too many stack frames are created.
# STR
- Create a YAML file with one visitor (necessary), which can be even an empty file.

list.yaml

```
source: src
destination: build/list
eraseIfExists: true
visitors:
- ./build/visitors/list.js
packages:
    list-log.txt:
        files:
            includes:
            - "**/*.foo"
```
- Create a number, say 20, of small files with `.foo` extension (hint: create one and copy-paste; names are not important).
- Change `merger.js`: https://github.com/captainbrosset/packman/blob/master/libs/merger.js#L56
  Wrap line 56 with two calls which log current stack trace depth.
  
  ```
  console.log("> " + new Error().stack.match(/\sat\s/gi).length);
  vh.runVisitorsOnPhase(vh.phases.onFileEnd, visitors, [config, packageFileObject], callback);
  console.log(">>>>> " + new Error().stack.match(/\sat\s/gi).length);
  ```
- Run. We want to inspect current stack size, we'll have to increase trace limit (it defaults to 10 which is way too low).

`$ node --stack-trace-limit=10000 node_modules/packman/packman.js -c build/list.yaml -n`

The output we get:

```
 packman is starting

  info Getting started with: source=src, destination=build/at-list, eraseIfExists=true
  info Creating package list-log.txt
> 20
> 38
> 56
[cut]
> 308
> 326
> 344
> 362
  info Package build/at-list/list-log.txt created!

 packman did it again! Have a great day! (0.189 sec)

>>>>> 362
>>>>> 344
>>>>> 326
>>>>> 308
[cut]
>>>>> 56
>>>>> 38
>>>>> 20
```

So as we can see, we go deeper and deeper and only leave when everything's done.

So far so good, but `--stack-size=492` by default. If we create >550 `.foo` files, we'll exhaust the stack and get a `RangeError` because of this. It means that for any build with large number of files to iterate, we'd have to increase linearly the V8 stack size which is far from convenient.

**Comment by jakub-g** [comment]
So, in short, we can work around the issue temporarily by passing `--stack-size` equal to ~twice the number of files which have to be iterated.

**Comment by captainbrosset** [comment]
Basically fixed by using `process.nextTick` to delay execution till the next tick on a fresh stack. I know I should rather look into the way packages and files are processed instead, but this will work anyway.
I added an automated integration test running packman on 5000 files.

**Comment by captainbrosset** [comment]
0.2.8 contains this fix
